spring:
  datasource:
    url: jdbc:p6spy:h2:mem:isme;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    username: root
    password: 123456
  h2:
    console:
      enabled: true
  sql:
    init:
      schema-locations: classpath:db/h2.sql
      mode: always