# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检查并拉取代码
        uses: actions/checkout@v4

      # Cache all maven dependencies to speed up the workflow
      - name: 设置 JDK 17 环境
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Maven 构建 jar 包
        # 需要跳过测试，要不就提供测试数据库
        run: mvn -f pom.xml clean package -Dmaven.test.skip=true

      - name: 展示 target 目录
        run: ls -la target

      - name: 登录 docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: 构建 Docker 镜像,推送镜像到 docker hub
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/like_toutiao_api:latest

      - name: 部署到服务器
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          user: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          # 执行脚本
          script: |
            echo "Pulling Docker image..."
            docker pull crazyhuman/like_toutiao_api:latest

            echo "Stopping and removing existing container..."
            docker stop like_toutiao_server || true
            docker rm like_toutiao_server || true

            echo "Running new container..."
            docker run -d --name like_toutiao_server -v /etc/like_toutiao:/app/conf/ -p 8848:80 crazyhuman/like_toutiao_api:latest
            echo "Deployment completed!"
